 # contents of a minimal pyproject.toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "example_package_saileesawant"
version = "0.1.0"
dependencies = ["numpy"]

 # In pyproject.toml
 
[project.optional-dependencies]
test = ["pytest"]